SELECT *
FROM (SELECT JOB, DEPTNO, SAL FROM EMP)
         PIVOT (MAX(SAL)
        FOR JOB IN (
        'CLERK' AS CLERK,
        'SALESMAN' AS SALESMAN,
        'PRESIDENT' AS PRESIDENT,
        'MANAGER' AS MANAGER,
        'ANALYST' AS ANALYST)
        )
ORDER BY DEPTNO