SELECT
    DECODE(GROUPING(DEPTNO), 1, 'ALL_DEPT', DEPTNO)AS DEPTNO,
    DECODE(GROUPING(JOB), 1, 'ALL_JOB', JOB)AS JOB,
    COUNT (*), MAX(SAL), SUM(SAL), AVG(SAL)
FROM EMP
GROUP BY CUBE(DEPTNO, JOB)
ORDER BY DEPTNO, JOB